version: '3.9'

services:
  backend-sales-system:
    build: 
      context: .
      dockerfile: dockerfile
    image: nodejs-sales-system
    container_name: backend-sales-system
    ports:
      - "3333:3333"
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}