version: '3.9'

services:
  test-database:
    image: "bitnami/postgresql:latest"
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRESQL_DATABASE: test-database