version: '3.9'

services:
  database-postgres-sales-system-test:
    image: "bitnami/postgresql:latest"
    container_name: database-postgres-sales-system
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRESQL_DATABASE: database-postgres-sales-system-test