version: '3.9'

services:
  backend-sales-system:
    build: 
      context: .
      dockerfile: dockerfile
    image: nodejs-sales-system
    container_name: backend-sales-system
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      SESSION_TOKEN: ${SESSION_TOKEN}
      AUTOMATIC_EMAIL_USER: ${AUTOMATIC_EMAIL_USER}
      AUTOMATIC_EMAIL_PASS: ${AUTOMATIC_EMAIL_PASS}
      SUPPORT_EMAIL_USER: ${SUPPORT_EMAIL_USER}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
      AWS_BUCKET_REGION: ${AWS_BUCKET_REGION}
      AWS_BUCKET_ACCESS_USER_KEY: ${AWS_BUCKET_ACCESS_USER_KEY}
      AWS_BUCKET_ACCESS_USER_PASS: ${AWS_BUCKET_ACCESS_USER_PASS}

  database-postgres-sales-system-test:
    image: "bitnami/postgresql:latest"
    container_name: database-postgres-sales-system
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRESQL_DATABASE: database-postgres-sales-system-test