/* eslint-disable no-unused-vars */

export enum AccountTypeEnum {
  NORMAL = 'NORMAL',
  ADMIN = 'ADMIN',
}
export enum ProductConditionEnum {
  NEW = 'NEW',
  USED = 'GOOD',
  BAD = 'BAD',
}
export enum ProductTypeEnum {
  PRODUCT = 'PRODUCT',
  SERVICE = 'SERVICE',
}
export enum RoleEnum {
  TECHNICIAN = 'TECHNICIAN',
  ATTENDANT = 'ATTENDANT',
}
export enum OrderTypeEnum {
  SERVICE = 'SERVICE',
  SALE = 'SALE',
}
export enum PaymentMethodEnum {
  PIX = 'PIX',
  CASH = 'CASH',
  DEBIT_CARD = 'DEBIT_CARD',
  CREDIT_CARD = 'CREDIT_CARD',
  ESTIMATE = 'ESTIMATE',
  INSTALLMENTS = 'INSTALLMENTS',
}
export enum OrderStatusEnum {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  CANCELED = 'CANCELED',
  AWAITING_SUPPLY = 'AWAITING_SUPPLY',
}
export enum PaymentStatusEnum {
  OPEN = 'OPEN',
  ESTIMATED = 'ESTIMATED',
  INVOICED = 'INVOICED',
  FULFILLED = 'FULFILLED',
}
export enum ServiceStatusEnum {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  AWAITING_ADJUSTMENT = 'AWAITING_ADJUSTMENT',
}

export enum NfeDataRegimeTributarioEnum {
  SIMPLES_NACIONAL = 'SIMPLES_NACIONAL',
  SIMPLES_NACIONAL_EXCESSO_SUBLIMITE = 'SIMPLES_NACIONAL_EXCESSO_SUBLIMITE',
  REGIME_NORMAL = 'REGIME_NORMAL',
  SIMPLES_NACIONAL_MICROEMPRESA_MUNICIPAL = 'SIMPLES_NACIONAL_MICROEMPRESA_MUNICIPAL',
  ESTIMATIVA = 'ESTIMATIVA',
  MICROEMPREENDEDOR_INDIVIDUAL = 'MICROEMPREENDEDOR_INDIVIDUAL',
}

export enum NfeDataCodigoRegimeTributarioEnum {
  SIMPLES_NACIONAL = '1',
  SIMPLES_NACIONAL_EXCESSO_SUBLIMITE = '2',
  REGIME_NORMAL = '3',
  SIMPLES_NACIONAL_MICROEMPRESA_MUNICIPAL = '4',
  ESTIMATIVA = '5',
  MICROEMPREENDEDOR_INDIVIDUAL = '6',
}

export enum ValidateMessagesEnum {
  DATE_ON_ISO = 'Invalid date format. Expected ISO 8601 string.',
}
