name: Run E2E Tests

on:
  pull_request:
    branches:
      - development

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test-database
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - run: corepack enable && corepack prepare pnpm@latest --activate

      - run: pnpm install

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432; do
            sleep 2
          done

      - name: Run E2E Tests
        run: pnpm run test:e2e
        env:
          NODE_ENV: "test"
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/test-database"
          FRONTEND_URL: "http://localhost:3001"
          PORT: 3000
          SESSION_TOKEN: "a6971c1133893760ffee00b8b0ecb0d2"
          RESET_PASSWORD_TOKEN: "c6e24e395ddc7799c009a33efae320ca"
          AUTOMATIC_EMAIL_USER: "email@email.com"
          AUTOMATIC_EMAIL_PASS: "xx"
          SUPPORT_EMAIL_USER: "email@email.com"
          ADMIN_EMAIL_USER: "email@email.com"
          ADMIN_ACCOUNT_CNPJ: "10000000000001"
          ADMIN_ACCOUNT_PASSWORD: "xxxxxx"
          ADMIN_DELETE_PASSWORD: "xxxxxx"
          ADMIN_UPDATE_PASSWORD: "xxxxxx"
          SYSTEM_ID: "acd1e1de-11e1-10a1-1abd-11e1e11111aa"
          ENCRYPT_KEY: "5bddb0f063633d227838091dc0466dafb31696f43e8a04706e65f92308488fc0"
          MERCADO_PAGO_KEY: "xx"
